/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/auth/login`; params?: Router.UnknownInputParams; } | { pathname: `/auth/index`; params?: Router.UnknownInputParams; } | { pathname: `/auth/signup`; params?: Router.UnknownInputParams; } | { pathname: `/../components/index`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ThemedButton`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ThemedCheckbox`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ThemedInput`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ThemedText`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ThemedView`; params?: Router.UnknownInputParams; } | { pathname: `/../constants/Colours`; params?: Router.UnknownInputParams; } | { pathname: `/../contexts/AuthContext`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/UseColorScheme`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/UseColorScheme.web`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/UseAuth`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/UseThemeColor`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/auth`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/auth/login`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/index`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/signup`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/index`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/ThemedButton`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/ThemedCheckbox`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/ThemedInput`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/ThemedText`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/ThemedView`; params?: Router.UnknownOutputParams; } | { pathname: `/../constants/Colours`; params?: Router.UnknownOutputParams; } | { pathname: `/../contexts/AuthContext`; params?: Router.UnknownOutputParams; } | { pathname: `/../hooks/UseColorScheme`; params?: Router.UnknownOutputParams; } | { pathname: `/../hooks/UseColorScheme.web`; params?: Router.UnknownOutputParams; } | { pathname: `/../hooks/UseAuth`; params?: Router.UnknownOutputParams; } | { pathname: `/../hooks/UseThemeColor`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/auth`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/auth/login${`?${string}` | `#${string}` | ''}` | `/auth/index${`?${string}` | `#${string}` | ''}` | `/auth/signup${`?${string}` | `#${string}` | ''}` | `/../components/index${`?${string}` | `#${string}` | ''}` | `/../components/ThemedButton${`?${string}` | `#${string}` | ''}` | `/../components/ThemedCheckbox${`?${string}` | `#${string}` | ''}` | `/../components/ThemedInput${`?${string}` | `#${string}` | ''}` | `/../components/ThemedText${`?${string}` | `#${string}` | ''}` | `/../components/ThemedView${`?${string}` | `#${string}` | ''}` | `/../constants/Colours${`?${string}` | `#${string}` | ''}` | `/../contexts/AuthContext${`?${string}` | `#${string}` | ''}` | `/../hooks/UseColorScheme${`?${string}` | `#${string}` | ''}` | `/../hooks/UseColorScheme.web${`?${string}` | `#${string}` | ''}` | `/../hooks/UseAuth${`?${string}` | `#${string}` | ''}` | `/../hooks/UseThemeColor${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/auth${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/auth/login`; params?: Router.UnknownInputParams; } | { pathname: `/auth/index`; params?: Router.UnknownInputParams; } | { pathname: `/auth/signup`; params?: Router.UnknownInputParams; } | { pathname: `/../components/index`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ThemedButton`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ThemedCheckbox`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ThemedInput`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ThemedText`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ThemedView`; params?: Router.UnknownInputParams; } | { pathname: `/../constants/Colours`; params?: Router.UnknownInputParams; } | { pathname: `/../contexts/AuthContext`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/UseColorScheme`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/UseColorScheme.web`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/UseAuth`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/UseThemeColor`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/auth`; params?: Router.UnknownInputParams; };
    }
  }
}
